intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{opensim}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

#obja{*}: cxx.poptions += -DLIBOPENSIM_STATIC_BUILD
#objs{*}: cxx.poptions += -DLIBOPENSIM_SHARED_BUILD

# Export options.
#
lib{opensim}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

#liba{opensim}: cxx.export.poptions += -DLIBOPENSIM_STATIC
#libs{opensim}: cxx.export.poptions += -DLIBOPENSIM_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{opensim}: bin.lib.version = "-$version.project_id"
else
  lib{opensim}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libopensim/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libopensim/
  install.subdirs = true
}
