import libs = libopensim%lib{osimTools}

exe{driver}: cxx{driver} $libs testscript

# See library buildfile for details.
#
obj{driver}: cxx.poptions += -DSPDLOG_COMPILED_LIB \
                             -DSWIG_PYTHON
